version: '3.4'

services:
  jupyterhub:
    image: jupyterhub
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./Dockerfile:/srv/jupyterhub/Dockerfile
